"""add performed_by to TaskLog

Revision ID: 7bde2700a308
Revises: 7b99391bfa8b
Create Date: 2025-10-16 17:05:11.053686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bde2700a308'
down_revision: Union[str, Sequence[str], None] = '7b99391bfa8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_logs', sa.Column('new_value', sa.JSON(), nullable=True))
    op.add_column('task_logs', sa.Column('old_value', sa.JSON(), nullable=True))
    op.add_column('task_logs', sa.Column('performed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_logs', 'users', ['performed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_logs', type_='foreignkey')
    op.drop_column('task_logs', 'performed_by')
    op.drop_column('task_logs', 'old_value')
    op.drop_column('task_logs', 'new_value')
    # ### end Alembic commands ###
